Урок 4. Завдання 1-12
neylovimuu/braveit pull request #13
Opened 2024-07-10 09:13 UTC by neylovimuu

Накрутив такого що ледве повернув все дякуючи Артему. дозвольте змерджити.

2024-07-10 21:23 UTC, prokopiff requested changes
Непогано, всі недоліки не суттєві

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskEight.java
> +/**
Після імпортів треба порожній рядок

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskEight.java
> +            System.out.println(sum);
Відступ з'їхав

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskEleven.java
> +/**
Після імпортів треба порожній рядок

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskEleven.java
> +
Зайвий рядок

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskFive.java
> +        System.out.println("Шістнадцятирічне: " + hexNumber);
Вісімкове і шістнадцяткове

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskNine.java
> +/**
Після імпортів треба порожній рядок

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskNine.java
> +        int one = 1;
Назва змінної мені не подобається, просто `i` було б краще, так звичніше

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskSix.java
> +}
Знову - це зараз не важливо, але бісить, коли підсвічено, що нема нового рядка в кінці файлу

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskTwelve.java
> +/**
Тут теж треба порожній рядок

2024-07-10 21:23 UTC, prokopiff commented on src/java/lesson4/TaskTwelve.java
> +            number ++;
Я вже багато разів писав коменти, що навколо операторів треба пробіли, але із унарними не треба.
```java
++i;
i++;
i = -i;
```

2024-07-11 06:34 UTC, artbelmeha commented on src/java/lesson4/TaskNine.java
> +        int one = 1;
Погоджуюсь що назва змінної не дуже, але `i` теж не варіант, то хіба в циклі можна залишати змінну з такою назвою

2024-07-11 06:37 UTC, artbelmeha commented on src/java/lesson4/TaskTwo.java
> +        do {
```suggestion
    public static void main(String[] args){
        int number = -100;
        do {
```

2024-07-11 06:39 UTC, artbelmeha commented on src/java/lesson4/TaskSix.java
> +}
Пошукай в налаштуваннях ідеї є опція автоматично додавати пустий рядок в кінець файлу

2024-07-11 14:06 UTC, neylovimuu commented on src/java/lesson4/TaskEight.java
> +/**
+ Додав

2024-07-11 14:07 UTC, neylovimuu commented on src/java/lesson4/TaskEight.java
> +            System.out.println(sum);
Поправив

2024-07-11 14:07 UTC, neylovimuu commented on src/java/lesson4/TaskEleven.java
> +/**
+ поправив

2024-07-11 14:08 UTC, neylovimuu commented on src/java/lesson4/TaskEleven.java
> +
Видалив зайвий рядок

2024-07-11 14:09 UTC, neylovimuu commented on src/java/lesson4/TaskFive.java
> +        System.out.println("Шістнадцятирічне: " + hexNumber);
Виправив

2024-07-11 14:10 UTC, neylovimuu commented on src/java/lesson4/TaskNine.java
> +/**
+ виправив

2024-07-11 14:12 UTC, neylovimuu commented on src/java/lesson4/TaskNine.java
> +        int one = 1;
переіменував на dataOne

2024-07-11 14:27 UTC, neylovimuu commented on src/java/lesson4/TaskSix.java
> +}
Наче знайшов в налаштуваннях, буду перевіряти чи працює.

2024-07-11 14:32 UTC, neylovimuu commented on src/java/lesson4/TaskTwelve.java
> +            number ++;
Прибрав пробіл "number++;"

2024-07-11 14:35 UTC, neylovimuu commented on src/java/lesson4/TaskTwo.java
> +        do {
+

2024-07-12 10:58 UTC, prokopiff approved these changes

2024-07-12 11:02 UTC, merged