Lesson2task4-5
neylovimuu/braveit pull request #3
Opened 2024-06-26 12:31 UTC by neylovimuu

1.Реалізував метод конвертації градусів Фарангейта в градуси Цельсії
2. Зробив метод для конвертації дюймів у сантиметри.

2024-06-26 14:13 UTC, prokopiff requested changes

2024-06-26 14:13 UTC, prokopiff commented on src/java/lesson2/Lesson2task1to3.java
> +      double v= 1_0.0_1;
Бракує пробіла

2024-06-26 14:13 UTC, prokopiff commented on src/java/lesson2/lesson2task4.java
> +        double C = convertToCelsius(F);
Змінні треба називати з малої букви

2024-06-26 14:13 UTC, prokopiff commented on src/java/lesson2/lesson2task4.java
> +        DecimalFormat df = new DecimalFormat("#.##");        // виконав завдання і захотілось мені зменшити кількість знаків в фарингейтах після коми
Можеш ще почитати про `printf` тоді
Наприклад
```java
System.out.printf("%.2f", 0.12345);
```
виводить `0.12`

2024-06-26 14:13 UTC, prokopiff commented on src/java/lesson2/lesson2task5.java
> +        return (centimeter * 2.54); // тут я щось не розумію як компілятор розуміє що "centimeter" це саме "35.5"
Компілятор нічого не знає про значення параметра `centimeter`.

Це вже під час виконання програми на рядку 7 туди передається конкретне значення.

Дужки зайві.

2024-06-26 14:41 UTC, merged

2024-06-27 12:08 UTC, artbelmeha commented on src/java/lesson2/TaskFour.java
> +        System.out.println(faringate + " F = " + df.format(celsius) + " C ");
а чому залишив коментар?

2024-06-27 12:21 UTC, neylovimuu commented on src/java/lesson2/TaskFour.java
> +        System.out.println(faringate + " F = " + df.format(celsius) + " C ");
Привіт, лишив коментар для того. щоб той хто переглядав мій код пишався моєю завзятістю ) видалю :)